### ISSUE TITLE
Can we actually make it work

### ISSUE THREAD

**Issue by ATahma** [MatteoGisondi/TLDL#1]
##Is there something you would like us to make?##
yes the tool as a whole

**Is your feature request related to a problem? Please describe.**
the problem is that it doesn't work

**Describe the solution you'd like**
make TL;DL work

**Describe alternatives you've considered**
I'm dead set on this

**Additional context**
????

**Comment by MatteoGisondi** [comment]
It can work, I'll take a look Thursday.

**Comment by MatteoGisondi** [comment]
"Working" with python==3.6.13 with recent push, I'm impressed with how terrible everything is.

GUI is _functional_ and summaries are dirty (i.e. dirty_summer).

**Comment by ATahma** [comment]
Lmao I remember my wise choice of variable names at the end. I think we can put it on _backlog_ for now 

If you have time though I need some help with NextCloud ;)
